"""Guarded local-model agent integration."""

from ..gateway import (
    RUNTIME_SECURITY_CONTEXT_VERSION,
    RuntimeDerivedOutput,
    RuntimeSecurityContext,
)
from .evaluation import (
    LIVE_FIXTURE_VERSION,
    adversarial_live_scenarios,
    benchmark_runtime_security_metadata,
    benign_live_scenarios,
    run_live_ollama_evaluation,
    run_live_openai_compatible_evaluation,
)
from .factory import create_local_agent_model
from .loop import (
    LOCAL_AGENT_VERSION,
    SYSTEM_INSTRUCTION,
    SYSTEM_INSTRUCTION_HASH,
    TOOL_SCHEMA_HASH,
    AgentLimits,
    AgentRunResult,
    AgentRunStatus,
    GuardedLocalAgent,
    ModelTurnAudit,
)
from .model import (
    GenerationConfig,
    LocalAgentModel,
    ModelIdentity,
    ModelMessage,
    ModelResponse,
)
from .ollama import (
    OLLAMA_ADAPTER_VERSION,
    LoopbackJsonTransport,
    OllamaAdapterError,
    OllamaAgentAdapter,
    OllamaProtocolError,
    OllamaUnavailableError,
)
from .openai_compatible import (
    OPENAI_COMPATIBLE_LOCAL_ADAPTER_VERSION,
    OPENAI_COMPATIBLE_PROTOCOL_VERSION,
    OpenAICompatibleHTTPError,
    OpenAICompatibleLocalAgentAdapter,
    OpenAICompatibleLocalError,
    OpenAICompatibleLoopbackTransport,
    OpenAICompatibleProtocolError,
    OpenAICompatibleUnavailableError,
    normalize_openai_chat_response,
    normalize_openai_message,
)
from .protocol import (
    ACTION_PROTOCOL_VERSION,
    ACTION_SCHEMA,
    ALLOWED_MODEL_TOOLS,
    ActionProtocolError,
    ActionType,
    ExternalSendAction,
    FinalResponseAction,
    MemoryWriteAction,
    ToolCallAction,
    parse_action,
)

__all__ = [
    "ACTION_PROTOCOL_VERSION",
    "ACTION_SCHEMA",
    "ALLOWED_MODEL_TOOLS",
    "LOCAL_AGENT_VERSION",
    "LIVE_FIXTURE_VERSION",
    "OLLAMA_ADAPTER_VERSION",
    "OPENAI_COMPATIBLE_LOCAL_ADAPTER_VERSION",
    "OPENAI_COMPATIBLE_PROTOCOL_VERSION",
    "RUNTIME_SECURITY_CONTEXT_VERSION",
    "SYSTEM_INSTRUCTION",
    "SYSTEM_INSTRUCTION_HASH",
    "TOOL_SCHEMA_HASH",
    "ActionProtocolError",
    "ActionType",
    "AgentLimits",
    "AgentRunResult",
    "AgentRunStatus",
    "ExternalSendAction",
    "FinalResponseAction",
    "GenerationConfig",
    "GuardedLocalAgent",
    "LocalAgentModel",
    "LoopbackJsonTransport",
    "MemoryWriteAction",
    "ModelIdentity",
    "ModelMessage",
    "ModelResponse",
    "ModelTurnAudit",
    "OllamaAdapterError",
    "OllamaAgentAdapter",
    "OllamaProtocolError",
    "OllamaUnavailableError",
    "OpenAICompatibleHTTPError",
    "OpenAICompatibleLocalAgentAdapter",
    "OpenAICompatibleLocalError",
    "OpenAICompatibleLoopbackTransport",
    "OpenAICompatibleProtocolError",
    "OpenAICompatibleUnavailableError",
    "RuntimeDerivedOutput",
    "RuntimeSecurityContext",
    "ToolCallAction",
    "adversarial_live_scenarios",
    "benchmark_runtime_security_metadata",
    "benign_live_scenarios",
    "create_local_agent_model",
    "parse_action",
    "normalize_openai_chat_response",
    "normalize_openai_message",
    "run_live_ollama_evaluation",
    "run_live_openai_compatible_evaluation",
]
